### PR TITLE
Mozilla DeepSpeech

### PR DESCRIPTION
**Pull request by elggem**
You probably dont want to merge this, but I hacked in Mozilla DeepSpeech support into your script. It works, but error rate is still too high.

### CODE REVIEW

**Comment by alecive** [comment]
Hi @elggem ,

thanks for the PR! I quickly gave a look at the changed files, but here it seems like you modified critical parts of our code in order to make the Mozilla DeepSpeech work.. am I correct?

If this is the case, you may want to have another approach, i.e. to modify the repo in such a way that the user can choose either DeepSpeech or Google's one. It would be great to have some sort of plug-ins that people can configure and choose at startup.

Also, what is the reason behind your choice? is DeepSpeech better / faster than the current Google API we are using? Because the Google one is pretty good for us.

**Review by omangin — CHANGES_REQUESTED** [review]
As mentioned by @alecive, the API for Mozilla DeepSpeech (or any other) would need to be integrated in a modular way to keep the code compatible with several speech to text backends. The specific parameters would also need to be prefixed in some way.

**Comment by omangin** [comment]
Thanks @elggem for sharing the code.

As mentioned above, it is indeed not ready for merging (partly because the initial code was not designed to handle other APIs). Please feel free to complete your PR to address this, we welcome improvements to the package that are useful to others. In particular we might want to join some effort together if their is interest in such a package.

As asked by @alecive, we would also be glad to know more about your experience and the pros and cons of each back-end solutions.

**Comment by elggem** [comment]
Hey there! Yes, absolutely this needs to be modular. I just did a quick implementation here in the lab to test how good the performance is. I might have time in the coming weeks to make it modular and also put some instructions on setup, I will keep you posted once I do.

I was looking for offline solutions to Google Speech, and DeepSpeech seemed to be the most promising. It can run several times faster than real-time on a 1080Ti. Unfortunately in practice the quality of transcription was not yet good enough and it doesnt provide alternates with certainty scores, but I have no doubt by mid-2018 it will be on-par with Google. Then it will be a really nice offline and OSS alternative, hopefully with lower latency!

**Comment by alecive** [comment]
An offline solution would be indeed preferable to having to rely on slow requests to the cloud. Looking forward to your contributions then! 

I'll close this PR for the time being since it will not be merged in the short term.

**Pull request closed without merging**
